### Get All Category
GET http://localhost:3000/go/api/category
X-API-KEY: RAHASIA
Accept: application/json


### Get ById Category
GET http://localhost:3000/go/api/category/10
X-API-KEY: RAHASIA
Accept: application/json

### Crate Category
POST http://localhost:3000/go/api/category
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}


### Update Category
PUT http://localhost:3000/go/api/category/2
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "ssss"
}


### Delete  Category
DELETE http://localhost:3000/go/api/category/9
X-API-KEY: RAHASIA
Accept: application/json
